// src/data/data.ts
import { Customer } from "./types";

const customers: Customer[] = [
  {
    id: 1,
    name: "Vishal Kumar",
    title: "Full Stack Web Developer",
    address: "Amar Chapra (Saran), Patna, India",
    images: [],
  },
  {
    id: 2,
    name: "Alice Johnson",
    title: "Engineer",
    address: "456 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 3,
    name: "Emma Davis",
    title: "Sales Rep",
    address: "789 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 4,
    name: "Michael Lee",
    title: "Analyst",
    address: "101 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 5,
    name: "Sarah Brown",
    title: "Designer",
    address: "202 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 6,
    name: "David Rodriguez",
    title: "Developer",
    address: "303 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 7,
    name: "Lisa Nguyen",
    title: "Marketing",
    address: "404 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 8,
    name: "Ryan Wilson",
    title: "Consultant",
    address: "505 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 9,
    name: "Olivia Taylor",
    title: "Coordinator",
    address: "606 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 10,
    name: "James Carter",
    title: "Technician",
    address: "707 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 11,
    name: "Emily White",
    title: "Manager",
    address: "808 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 12,
    name: "Daniel Garcia",
    title: "Engineer",
    address: "909 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 13,
    name: "Sophia Martinez",
    title: "Sales Rep",
    address: "1010 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 14,
    name: "Logan Brown",
    title: "Analyst",
    address: "1111 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 15,
    name: "Mia Lopez",
    title: "Designer",
    address: "1212 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 16,
    name: "Benjamin Clark",
    title: "Developer",
    address: "1313 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 17,
    name: "Ava Rodriguez",
    title: "Marketing",
    address: "1414 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 18,
    name: "Ethan Nguyen",
    title: "Consultant",
    address: "1515 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 19,
    name: "Isabella Turner",
    title: "Coordinator",
    address: "1616 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 20,
    name: "Alexander Wright",
    title: "Technician",
    address: "1717 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 21,
    name: "Madison King",
    title: "Manager",
    address: "1818 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 22,
    name: "Elijah Hill",
    title: "Engineer",
    address: "1919 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 23,
    name: "Victoria Scott",
    title: "Sales Rep",
    address: "2020 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 24,
    name: "Dylan Green",
    title: "Analyst",
    address: "2121 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 25,
    name: "Sophie Hall",
    title: "Designer",
    address: "2222 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 26,
    name: "Jackson Adams",
    title: "Developer",
    address: "2323 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 27,
    name: "Natalie Baker",
    title: "Marketing",
    address: "2424 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 28,
    name: "Christopher Reed",
    title: "Consultant",
    address: "2525 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 29,
    name: "Zoe Cooper",
    title: "Coordinator",
    address: "2626 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 30,
    name: "Connor Ross",
    title: "Technician",
    address: "2727 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 31,
    name: "Gabriella Morgan",
    title: "Manager",
    address: "2828 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 32,
    name: "Luke Cooper",
    title: "Engineer",
    address: "2929 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 33,
    name: "Lillian Kelly",
    title: "Sales Rep",
    address: "3030 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 34,
    name: "Grayson Bennett",
    title: "Analyst",
    address: "3131 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 35,
    name: "Addison Price",
    title: "Designer",
    address: "3232 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 36,
    name: "Scarlett Murphy",
    title: "Developer",
    address: "3333 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 37,
    name: "Nathan Rivera",
    title: "Marketing",
    address: "3434 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 38,
    name: "Grace Perry",
    title: "Consultant",
    address: "3535 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 39,
    name: "Carter Evans",
    title: "Coordinator",
    address: "3636 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 40,
    name: "Hannah Richardson",
    title: "Technician",
    address: "3737 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 41,
    name: "Liam Richardson",
    title: "Manager",
    address: "3838 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 42,
    name: "Zoey Henderson",
    title: "Engineer",
    address: "3939 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 43,
    name: "Avery Carter",
    title: "Sales Rep",
    address: "4040 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 44,
    name: "Jackson Gonzalez",
    title: "Analyst",
    address: "4141 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 45,
    name: "Abigail Roberts",
    title: "Designer",
    address: "4242 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 46,
    name: "David Cook",
    title: "Developer",
    address: "4343 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 47,
    name: "Emma Phillips",
    title: "Marketing",
    address: "4444 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 48,
    name: "Henry Stewart",
    title: "Consultant",
    address: "4545 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 49,
    name: "Mila Morris",
    title: "Coordinator",
    address: "4646 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 50,
    name: "Owen Henderson",
    title: "Technician",
    address: "4747 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 51,
    name: "Aria Martinez",
    title: "Manager",
    address: "4848 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 52,
    name: "Eli Simmons",
    title: "Engineer",
    address: "4949 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 53,
    name: "Levi Flores",
    title: "Sales Rep",
    address: "5050 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 54,
    name: "Nora Russell",
    title: "Analyst",
    address: "5151 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 55,
    name: "Hazel Jenkins",
    title: "Designer",
    address: "5252 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 56,
    name: "Isaac Diaz",
    title: "Developer",
    address: "5353 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 57,
    name: "Bella Butler",
    title: "Marketing",
    address: "5454 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 58,
    name: "Lucas Myers",
    title: "Consultant",
    address: "5555 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 59,
    name: "Aurora Kim",
    title: "Coordinator",
    address: "5656 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 60,
    name: "Greyson Webb",
    title: "Technician",
    address: "5757 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 61,
    name: "Elena Barnes",
    title: "Manager",
    address: "5858 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 62,
    name: "Mateo Washington",
    title: "Engineer",
    address: "5959 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 63,
    name: "Brooklyn Sanders",
    title: "Sales Rep",
    address: "6060 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 64,
    name: "Ella Henderson",
    title: "Analyst",
    address: "6161 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 65,
    name: "Xavier Gomez",
    title: "Designer",
    address: "6262 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 66,
    name: "Samantha Wood",
    title: "Developer",
    address: "6363 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 67,
    name: "Dominic Torres",
    title: "Marketing",
    address: "6464 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 68,
    name: "Violet Barnes",
    title: "Consultant",
    address: "6565 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 69,
    name: "Leo Coleman",
    title: "Coordinator",
    address: "6666 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 70,
    name: "Julia Foster",
    title: "Technician",
    address: "6767 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 71,
    name: "Brody Richardson",
    title: "Manager",
    address: "6868 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 72,
    name: "Peyton Howard",
    title: "Engineer",
    address: "6969 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 73,
    name: "Amelia Henderson",
    title: "Sales Rep",
    address: "7070 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 74,
    name: "Chase Baker",
    title: "Analyst",
    address: "7171 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 75,
    name: "Nevaeh Griffin",
    title: "Designer",
    address: "7272 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 76,
    name: "Gavin Simpson",
    title: "Developer",
    address: "7373 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 77,
    name: "Leah Grant",
    title: "Marketing",
    address: "7474 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 78,
    name: "Colton Stewart",
    title: "Consultant",
    address: "7575 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 79,
    name: "Adeline Harris",
    title: "Coordinator",
    address: "7676 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 80,
    name: "Rhett Mitchell",
    title: "Technician",
    address: "7777 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 81,
    name: "Amaya Gomez",
    title: "Manager",
    address: "7878 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 82,
    name: "Nicolas Alexander",
    title: "Engineer",
    address: "7979 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 83,
    name: "Mackenzie Bailey",
    title: "Sales Rep",
    address: "8080 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 84,
    name: "Elias Bell",
    title: "Analyst",
    address: "8181 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 85,
    name: "Layla Murphy",
    title: "Designer",
    address: "8282 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 86,
    name: "Jordan Powell",
    title: "Developer",
    address: "8383 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 87,
    name: "Skylar Hughes",
    title: "Marketing",
    address: "8484 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 88,
    name: "Bentley Butler",
    title: "Consultant",
    address: "8585 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 89,
    name: "Kylie Marshall",
    title: "Coordinator",
    address: "8686 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 90,
    name: "Zander Bell",
    title: "Technician",
    address: "8787 Cherry St, Metropolis, USA",
    images: [],
  },
  {
    id: 91,
    name: "Alexa Wright",
    title: "Manager",
    address: "8888 Cedar St, Cityville, USA",
    images: [],
  },
  {
    id: 92,
    name: "Tyler Ward",
    title: "Engineer",
    address: "8989 Elm St, Townburg, USA",
    images: [],
  },
  {
    id: 93,
    name: "Riley Ellis",
    title: "Sales Rep",
    address: "9090 Oak St, Villagetown, USA",
    images: [],
  },
  {
    id: 94,
    name: "Hudson Barker",
    title: "Analyst",
    address: "9191 Pine St, Hamletville, USA",
    images: [],
  },
  {
    id: 95,
    name: "Piper Sims",
    title: "Designer",
    address: "9292 Maple St, Boroughburg, USA",
    images: [],
  },
  {
    id: 96,
    name: "Eva Fox",
    title: "Developer",
    address: "9393 Cedar St, Township, USA",
    images: [],
  },
  {
    id: 97,
    name: "Austin Grant",
    title: "Marketing",
    address: "9494 Birch St, Villageville, USA",
    images: [],
  },
  {
    id: 98,
    name: "Brianna Holmes",
    title: "Consultant",
    address: "9595 Walnut St, Citytown, USA",
    images: [],
  },
  {
    id: 99,
    name: "Micah Porter",
    title: "Coordinator",
    address: "9696 Spruce St, Townsville, USA",
    images: [],
  },
  {
    id: 100,
    name: "Ivy Collins",
    title: "Technician",
    address: "9797 Cherry St, Metropolis, USA",
    images: [],
  },
];
for (let i = 101; i < 1000; i++) {
  customers.push({
    id: i,
    name: `Customer ${i}`,
    title: `Position ${i}`,
    address: `Address ${i}`,
    images: [],
  });
}

export default customers;
